name: Dev-Build-Deploy
on:
  push:
    branches:
      - main

jobs:
  # Job to Build Docker Image
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set TAG environment variable
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Debug TAG value
        run: echo "TAG value - ${{ env.TAG }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_NAME }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ secrets.TAG }}
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:${{ secrets.TAG }} .
          docker push ${{ secrets.ECR_REPOSITORY }}:${{ secrets.TAG }}
      - name: Deploy Stack to Dev
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.HOST_NAME }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.EC2_KEY }}
           port: ${{ secrets.PORT }}
           script: |
            cd ${{ secrets.TARGET_DIR_DEV }}
            if [ -f .env ]; then
              rm .env
            fi
            echo '${{ secrets.DEV_ENV }}' > .env
            ./deploy.sh ${{ secrets.TAG }}
